### ISSUE TITLE
Different document_dir for every bundle

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#145]
Now we set `document_dir` as global:
```yaml
elasticsearch:
    document_dir: "foo/documents"
    connections: ...
    managers: ...
```

Would be nice if `document_dir` could be set different for each bundle (needs more investigation) or manager (easy achievable). f.e:

```yaml
elasticsearch:
    connections: ...
    managers:
        default:
            connection:default
            mappings:
                - {bundle: "AcmeTestBundle", document_dir: "foo/documents"}
                - AcmeBlogBundle
```

Both cases should work IMO.

**Comment by saimaz** [comment]
Good idea @martiis. This would solve some issues we had before. How about this structure:

```
elasticsearch:
    connections: ...
    managers:
        default:
            connection:default
            mappings:
                AcmeBlogBundle: ~
                AcmeTestBundle:
                   document_dir: "foo/documents"
                   mapped_documents:
                       - Product
                       - Category
```
