### ISSUE TITLE
Mappings should be able to accept separate documents

### ISSUE THREAD

**Issue by trylika** [ongr-io/ElasticsearchBundle#185]
Ability to add only selected documents to specified index is needed, currently, all documents from one bundle are added to the same index. Sometimes, we need that documents have to be on separate indexes.

```
ongr_elasticsearch:
    ...
    managers:
        default:
            ...
            mappings:
                - ONGRMatchMergeBundle:Settings
```
