### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cordoval** [ongr-io/ElasticsearchBundle#202]
if i have to search and sift through data items with 4 index records like patient, case, network, users, do i have to configure 4 of these: 

```yaml
    patient:
            hosts:
                - { host: 127.0.0.1:9200 }
            index_name: pcna_patient
            settings:
                refresh_interval: -1
                number_of_replicas: 1
        case:
            hosts:
                - { host: 127.0.0.1:9200 }
            index_name: pcna_case
            settings:
                refresh_interval: -1
                number_of_replicas: 1

... ?
```
?
