### ISSUE TITLE
Allow setting hostname and port separately for connection as an alternative

### ISSUE THREAD

**Issue by Im0rtality** [ongr-io/ElasticsearchBundle#244]
Current:
```yaml
ongr_elasticsearch:
    connections:
        default:
            hosts:
                - { host: "127.0.0.1:9200" }
            index_name: foo

```

Alternative way of specifying same:
```yaml
ongr_elasticsearch:
    connections:
        default:
            hosts:
                - { host: "127.0.0.1" port: "9200" }
            index_name: foo
```

Allows for cleaner/more consistent configs as we don't need to store concatenated parameter.
