### ISSUE TITLE
how to configure the analysis  IK in the  document mapping？

### ISSUE THREAD

**Issue by laurusCN** [ongr-io/ElasticsearchBundle#283]
how to configure the analysis  IK in the  document mapping？

``` code
class Topic implements DocumentInterface
{
    use DocumentTrait;

    /**
     * @var string
     *
     * @ES\Property(name="name", type="string", analyzer="ik_analyzer")
     */
    public $name;
}
```

the mapping error ?

**Comment by chyzas** [comment]
Hello, it looks like that the analyzer is not loaded. As I found in [ik_analyzer description](https://github.com/medcl/elasticsearch-analysis-ik/blob/master/README.textile) it should work like this:
(config example)
```yml
ongr_elasticsearch:
    connections:
        default:
            hosts:
                - { host: 127.0.0.1:9200 }
            index_name: acme_index
            settings:
                analysis:
                    analyzer:
                        ik:
                            alias: [ik_analyzer]
                            type: org.elasticsearch.index.analysis.IkAnalyzerProvider
```

Then property annotation should be defined like this:

```php
class Topic implements DocumentInterface
{
    use DocumentTrait;

    /**
     * @var string
     *
     * @ES\Property(name="name", type="string", analyzer="ik")
     */
    public $name;
}
```
