### ISSUE TITLE
Log all queries to DEBUG level

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#351]
Doctrine is logging all queries to DEBUG level. Maybe it's a good idea to do the same in ESB.

There could be a parameter to disable this, for example when too many queries are being generated.

This can be helpful when running console comands using `-vvv` option. Queries will be written on screen.

**Comment by tautrimas** [comment]
Also, elasticsearch-php might already be logging all queries, but it might be disabled in our configurations.

**Comment by martiis** [comment]
In debug level there are quite a lot of logs. Maybe better I'll implement level in confg tree

**Comment by tautrimas** [comment]
Yes, but we were solving issue https://github.com/elastic/elasticsearch-php/issues/204 related to logging. Maybe logs are produced in that lower level so no implementation needed on our side?

**Comment by martiis** [comment]
We are enabling logging and providing configuration for them, also I think log level should be in config :)

**Comment by trickreich** [comment]
@martiis This isn't working for me..

My config:

```
ongr_elasticsearch:
    managers:
        <indexName>:
            index:
                hosts:
                    - <esIp>:<esHost>
                index_name: <indexName>
                settings:
                    refresh_interval: -1
                    number_of_replicas: 0
                    number_of_shards: 5
            mappings:
                - <Class>
            logger:
                level: debug
                enabled: true
```
