### ISSUE TITLE
Host configuration for multiple environments

### ISSUE THREAD

**Issue by mkleint-magari** [ongr-io/ElasticsearchBundle#436]
Heyho all,

we have a problem, when using the bundle with different environment settings. 

At the moment we have to put the whole configuration for your bundle in all of our environment configuration files. Way better would be, to place the general configuration in config.yml and then just put things that differ from general configuration into each environment-specific config file.

We want to use the bundle for all environments but production with this configuration:

```
ongr_elasticsearch:
    connections:
        category_connection:
            hosts:
                - { host: 127.0.0.1:9200 }
            index_name: categories
            settings:
                refresh_interval: -1
                number_of_replicas: 0
    managers:
        default:
            connection: category_connection
            mappings:
                - OurBundlePath
```

and in production environment we want to use another ip for the elasticsearch host.

So I would expect to put the general configuration (above) into config.yml and just the following one into config_production.yml (which as far as I know the common behaviour of symfony's configuration file handling):

```
ongr_elasticsearch:
    connections:
        category_connection:
            hosts:
                - { host: our.elastic.host.ip:9200 }
```

At the moment this does not work. Seems like, the general and environment-specific configurations are merged and all of their hosts get configured, which means, the system tries to connect to 127.0.0.1 in production where no elastic server is listening.

Did you get what I mean somehow? :)

Can you fix that?

**Comment by saimaz** [comment]
I'll take a look. The way how it works now is not very good. It should be like you described.

**Comment by murnieza** [comment]
Yes there are problems in configuration merging, but in your particular case you can use single configuration and only change ip parameter depending on environment. Configuration would look like this:

```yml
ongr_elasticsearch:
    connections:
        category_connection:
            hosts:
                - { host: %es_host% }
            index_name: categories
            settings:
                refresh_interval: -1
                number_of_replicas: 0
    managers:
        default:
            connection: category_connection
            mappings:
                - OurBundlePath
```

Then in `parameters.yml`:
```yml
parameters:
    es_host: 127.0.0.1:9200
```

In any other environment you can change it, e.g. `parameters_prod.yml`:
```yml
parameters:
    es_host: 127.1.1.1:9200
```

Does it solve your problem now?
