### ISSUE TITLE
Index creation fails if connection's settings are not defined

### ISSUE THREAD

**Issue by asev** [ongr-io/ElasticsearchBundle#497]
Empty settings should be converted to empty object instead of empty array.

```
ongr_elasticsearch:
    connections:
        default:
            index_name: acme
    managers:
        default:
            connection: default
            mappings:
                - AppBundle
```

and `app/console ongr:es:index:create` fails because settings parts on creation query is an empty array.
