### ISSUE TITLE
The auth configuration seems not to be used.

### ISSUE THREAD

**Issue by chirimoya** [ongr-io/ElasticsearchBundle#679]
Hi there,

we have activated the shield plugin for ES and configured the ONGR Bundle like described below. I've debugged into the `ConnectionFactory` class, but it seems that the auth configurations doesn't get used.

```yml
# Ongr Elasticsearch
ongr_elasticsearch:
    connections:
        default:
            hosts:
                - %elasticsearch_host%
            auth:
                username: %elasticsearch_username%
                password: %elasticsearch_password%

**Comment by saimaz** [comment]
Seems like this config is a legacy from very old versions of the bundle. I would suggest you to put credentials directly in the host:

```
ongr_elasticsearch:
    connections:
        default:
            hosts:
                - 'http://user:pass@127.0.0.1:9200'
```

I think we definitely will remove `auth` option in next major release.
