### ISSUE TITLE
result pagination

### ISSUE THREAD

**Issue by dijadev** [ongr-io/ElasticsearchBundle#709]
Hi! Is there any way to paginate the results ?
Thanks in advance,

**Comment by saimaz** [comment]
For pagination, data filtering and much more you can use [FilterManager bundle](https://github.com/ongr-io/FilterManagerBundle).

**Comment by MichaelMure** [comment]
You can also use KnpPaginatorBundle with a custom paginator as follow:

```php
class ElasticSearchSubscriber implements EventSubscriberInterface
{
    public function items(ItemsEvent $event)
    {
        if(is_array($event->target) && count($event->target) === 2 &&
            reset($event->target) instanceof Repository && end($event->target) instanceof Search) {

            /** @var Repository $repo */
            /** @var Search $search */
            list($repo, $search) = $event->target;

            $search->setFrom($event->getOffset());
            $search->setSize($event->getLimit());

            $results = $repo->findDocuments($search);

            $event->count = $results->count();

            $event->items = [];
            foreach ($results as $result) {
                $event->items[] = $result;
            }

            $event->stopPropagation();
        }
    }
    public static function getSubscribedEvents()
    {
        return [ 'knp_pager.items' => ['items', 1]];
    }
}
```

```
<service id="acme.elasticsearch.subscriber" class="ACME\Bundle\MyBundle\ElasticSearchSubscriber">
    <tag name="knp_paginator.subscriber" />
</service>
```

```php
$results = $this->get('knp_paginator')->paginate(
    [$repo, $search],
    $request->query->get('page', 1),
    is_null($quantity) ? 30 : $quantity,
    $options
);
```

**Comment by einorler** [comment]
I'd say it's easier with `FilterManagerBundle`. All you need is add config:

```yml
ongr_filter_manager:
    managers:
        search_list:
            filters:
                - search_pager
            repository: 'es.manager.default.product'
    filters:
        pager:
            search_pager:
                request_field: 'page'
                count_per_page: 5
```
Handle the request in controller:
```php
public function listAction(Request $request)
    {
        $searchList = $this->get(ONGRFilterManagerExtension::getFilterManagerId('search_list'))
                      ->handleRequest($request);

        return $this->render(
          'AppBundle:Product:list.html.twig',
          [
            'filters' => $searchList->getFilters(),  // Returns filters container array
            'products' => $searchList->getResult(),  //Returns result iterator
          ]
        );                  
    }
```
And after you form your list, add the pager bar in the template:
```twig
{% set pagerFilter = filter_manager.getFilters().search_pager %}
{{ ongr_paginate(pagerFilter.pager, app.request.attributes.get('_route'), pagerFilter.getUrlParameters()) }}
```

Plus with this, you can add any other filters at any time, including sorting, searching, choices and more

**Comment by dijadev** [comment]
Thank you for your feedBacks ,

I've  tried to use FilterManagerBundle but I could not find a way to combine document_value filters pagination !
I will use KnpPaginatorBundle I am earlady familier with it .

Thanks

**Comment by einorler** [comment]
Which one works for you best. 

In case that you described here, you need to use 2 filters in `FilterManager`: `document_value` for filtering specific documents on request data and `pager` for paginating results. `pager` is a separate filter and you can add as many filters as you want to a single filter manager

**Comment by einorler** [comment]
Also, we are currently working on improving the documentation of that particular bundle, so if you found any places which you found confusing in the docs, please take time to make an issue in FilterManager repo about it

**Comment by dijadev** [comment]
Yah it is what I tried to do I wanted to paginate results of ducument_value filter

This is what I put into the config file:

```
 ongr_filter_manager:
    managers:
        products_bycategory_list:
            filters:
                - product_filter
                - product_pager
            repository: 'es.manager.default.product'
    filters:
        document_value:
            category_filter:
                request_field: category# Use only `document` value, unless you have your own router.
                document_field: category_id
        pager:
            product_pager:
                request_field: 'page'
                count_per_page: 5
```
But it is not documented How to use this two filters together in the controller.

**Comment by einorler** [comment]
Well, first of all, you specified `category` in the `request_field`, even though the doc specifically sais it should be `document` :) But I admit, that the docs in this bundle are a bit fuzzy since we are in the process of moving to the `2.0` at the moment. Tell me which version of FilterManager did you use and I will help you with configuration.

On the topic of controller, its very simple. get the filter manager service and do

```php
$result = $filterManager->handleRequest($requst);
```

I described it in more detail above. It's as simple as that, doesn't matter how many filters there are, this action is always the same.

**Comment by dijadev** [comment]
I thought that not specifying the param name suppose that my action should receive the only filter field as param :
`public function filterByCategoryAction(Request $request, $category)
{ ... }
But in my case my action receives several params
 `public function filterByCategoryAction(Request $request, $category,$fielter2,$fielter3){ ... }` 

How could it know which one is the right request_field then and how to pass the other filters to the filter manager ?

**Comment by einorler** [comment]
Not sure I understand your question. Let's breake it down. 

1) Firstly, the filters are passed to the filter manager in configuration when you specify:

```yml
managers:
        products_bycategory_list:
            filters:
                - product_filter
                - product_pager
```
Here `products_bycategory_list` is the filter manager that will have 2 filters.

2) The values on which the filters will operate are taken from the request query (that's what the `request_field` is for)

3) The `document_value` filter is 'special' in a sense that it is used together with [ONGR Router](https://github.com/ongr-io/RouterBundle).  This was also specified in the docs. This is why it needs `document` to be specified in `request_field` - it always takes the document from the ONGR router. And you need to specify the `field` of the document (which you did not), that holds the value you want. 

As you can see, the configuration is important here, and it changes in the upcoming `2.0`, so if you are using the `1.0` you should refer to the docs in the `Resources/doc` directory, instead of the `docs.ongr.io` and I can't fully help you without knowing which version you are running on
