### ISSUE TITLE
Docs missing for single document mapping

### ISSUE THREAD

**Issue by asev** [ongr-io/ElasticsearchBundle#757]
With configuration like this:
```
ongr_elasticsearch
    managers:
        traffic:
            connection: traffic
            mappings:
                - AppBundle
        locations:
            connection: locations
            mappings:
                - AppBundle
```

I got all documents defined for both indexes. So, traffic index has location document and looks like this:
![image](https://cloud.githubusercontent.com/assets/10020928/23356078/381901aa-fce1-11e6-852f-fbc7614fe1e2.png)

I solved this issue by adding specific documents to mappings:
```
ongr_elasticsearch
    managers:
        traffic:
            connection: traffic
            mappings:
                - AppBundle:TrafficDocument
        locations:
            connection: locations
            mappings:
                - AppBundle:LocationDocument
```

The problem, that this seems undocumented feature. Or at least I was not able to find such configuration in http://docs.ongr.io/ElasticsearchBundle/mapping
