### ISSUE TITLE
Stopwatch service on production environment

### ISSUE THREAD

**Issue by shine60vn** [ongr-io/ElasticsearchBundle#787]
Hi @saimaz ,
I'm facing a memory leaking issue when running a command with `-e prod` that executes many queries (~1,4 mil). I found the cause is stopwatch service. It's always available even on `prod` environment. I know that the developers may want to see the profiler on production, but I think we should add a config in my case to a command that needs to execute a huge amount of queries.
What do you think?

**Comment by saimaz** [comment]
It should not calculate query time in the production. Unless you enable profiler in the configuration, but by default, it should be disabled. 

Can you check if you have this config enabled?

**Comment by shine60vn** [comment]
I thought the stopwatch service is always available since this commit https://github.com/symfony/symfony/commit/e86fe91d7069fdb557e882ae77c4f7ab3cd17f4b. Here is my profiler configuration:
```
web_profiler:
    toolbar: true
    intercept_redirects: false
```
and it's only in `config_dev.yml`

**Comment by saimaz** [comment]
I was talking about elasticsearch manager's configuration, do you have profiler enabled in ther, e.g.:

```
ongr_elasticsearch:
    profiler: true  <----- here
    analysis:
        filter:
         .....
    managers:
        default:
        ........
```
