### ISSUE TITLE
perform search in a specific index

### ISSUE THREAD

**Issue by dijadev** [ongr-io/ElasticsearchBundle#792]
Hi!
I have indices created dynamically in this way project_id_of_the_project (project_1, project_2...)
I use this mapping
```
        project:
            index:
                hosts:
                    - %elasticsearch_host%:%elasticsearch_port%
                index_name: project*
```
and I can perform search using the global index name which allows to explore all indices
` $repo_es = $this->get('es.manager.project')->getRepository('AppBundle:project');`

My question is how can i do my search in a specific index instead of exploring all matching indices ? something like ;
` $repo_es = $this->get('es.manager.project_1')->getRepository('AppBundle:project');`

Thank you !
