### ISSUE TITLE
Create new index 404

### ISSUE THREAD

**Issue by Chitzi** [ongr-io/ElasticsearchBundle#806]
I've tried to create the new index with ongr:es:index:create but I've got this error. Naturally there is no index, I'm trying to create it.

`php console ongr:es:index:create --if-not-exists`

```
[Elasticsearch\Common\Exceptions\Missing404Exception]
  {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"correctindex","index_uuid":"_na_","index":"correctindex"}],"type  ":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"correctindex","index_uuid":"_na_","index":"correctindex"},"status":404}
```

Configuration:

```
ongr_elasticsearch:
    managers:
        default:
            index:
                hosts:
                    - localhost:9200
                index_name: correctindex
            mappings:
                - CoreBundle
```

```
curl localhost:9200
{
  "name" : "B-Q46Kr",
  "cluster_name" : "Server",
  "cluster_uuid" : "SZnpRlyeRkqesZEGB_faAQ",
  "version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}
```
