### ISSUE TITLE
Class mapping instead of bundle mapping

### ISSUE THREAD

**Issue by toooni** [ongr-io/ElasticsearchBundle#838]
The mapping is currently auto-loaded from a directory (`Document`) in a bundle.
```
ongr_elasticsearch:
    managers:
        default:
            index:
                index_name: acme
            mappings:
                - AppBundle
```
Since ES6 only allows one document type per index (except parent/child) I recommend using something like this:
```
ongr_elasticsearch:
    managers:
        default:
            index:
                index_name: acme
                class: AppBundle\Document\AcmeProduct
```

In cases of parent/child documents, `AcmeProduct` in the example is the parent and the child is defined in it.

This makes it possible to have multiple indexes in one bundle - which isn't yet.

Are there other solutions which may be better? What are the plans? I might be able to help out a bit.
