### ISSUE TITLE
Bulk Commit issue

### ISSUE THREAD

**Issue by abame** [ongr-io/ElasticsearchBundle#856]
https://github.com/ongr-io/ElasticsearchBundle/blob/41a1adffb1e9c45bfcc40882e56b1e135eb014b6/Service/Manager.php#L495-L497

Has anyone else had the problem of missing some documents due to bulk commit size? 

I had an issue with the default value of bulkCommitSize when less than 100 documents are left to commit. They are not persisted. A quick solutions is to set the bulkCommitSize to 1 but not a good one.

**Comment by saimaz** [comment]
This is a strange issue. What you can do is to create a onKernelResponse subscriber and commit in your active manager. 

e.g. 
````php
namespace AppBundle\EventListener;

use ONGR\ElasticsearchBundle\Service\Repository;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class KernelEventSubscriber implements EventSubscriberInterface
{
    /** @var Repository */
    private $productRepository;

    public function __construct($productRepository)
    {
        $this->productRepository = $productRepository;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::RESPONSE => 'onKernelResponse'
        ];
    }

    public function onKernelResponse(FilterResponseEvent $event): void
    {
        $this->productRepository->getManager()->commit();
    }
}
````

The `$productRepository` is preloaded in the `services.yml`:

````yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $productRepository: '@es.manager.default.product'
````
