### ISSUE TITLE
Amazon Elastic Search connection problem

### ISSUE THREAD

**Issue by WarGot-by** [ongr-io/ElasticsearchBundle#928]
I've created something like this.
```
ongr_elasticsearch:
    source_directories:
        - /src/Document
    indexes:
        App\Document\RightsholderDocument:
            hosts: [https://userlogin:password@amazon-elastic-search-address.us-east-1.es.amazonaws.com:443] 
```

I get an error when I connect. More precisely, after the command 
```
php bin/console ongr:es:index:create
```
is executed.
 ```
 {"message":"Authorization header requires 'Credential' parameter. Authoriza  
  tion header requires 'Signature' parameter. Authorization header requires '  
  SignedHeaders' parameter. Authorization header requires existence of either  
   a 'X-Amz-Date' or a 'Date' header. Authorization=Basic UUFLSUFYNVJFUDdEVVJ  
  ="}  
```

Maybe somebody's had a similar problem ?
